# Generated by Django 6.0 on 2025-12-11 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('blood_oxygen', models.FloatField(blank=True, null=True)),
                ('sbp', models.IntegerField(blank=True, null=True)),
                ('dbp', models.IntegerField(blank=True, null=True)),
                ('ecg_sensor_frame', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('diet_summary', models.TextField(blank=True, null=True)),
                ('mental_health_summary', models.TextField(blank=True, null=True)),
                ('model_context', models.TextField(blank=True, null=True)),
                ('premium_plan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accepted', models.BooleanField(default=False)),
                ('access_diet_data', models.BooleanField(default=False)),
                ('access_vital_signs_data', models.BooleanField(default=False)),
                ('monitored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='app.userprofile')),
                ('monitored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='app.userprofile')),
            ],
        ),
    ]
