# Generated by Django 5.2.9 on 2025-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_config_id_alter_devicerecords_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicerecords",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicerecords",
            name="gender",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
